import pandas as pd
import matplotlib.pyplot as plt
score = pd.read_csv('C:/Users/文/Desktop/student_score.csv',encoding='gbk')
avg_math=score.高数.mean()
avg_english=score.英语.mean()
avg_python=score.python.mean()
sum_score=score.高数+score.英语+score.python
max_math=score.高数.max()
max_english=score.英语.max()
max_python=score.python.max()
min_math=score.高数.min()
min_english=score.英语.min()
min_python=score.python.min()
fig=plt.figure(num=1,figsize=(30,10),dpi=80,facecolor='orange')
plt.subplot(221)
plt.plot(score.学号,sum_score)
plt.xticks(range(1001,1031),rotation=60)
plt.title('学生总成绩分布折线图',fontproperties='STSong',fontsize=15)
plt.xlabel('学号',fontproperties='STSong',fontsize=15)
plt.ylabel('学生总成绩',fontproperties='STSong',rotation=360,fontsize=10)
plt.grid()
plt.subplot(222)
plt.scatter(score.学号,sum_score)
plt.xticks(range(1001,1031),rotation=60)
plt.title('学生总成绩分布散点图',fontproperties='STSong',fontsize=15)
plt.xlabel('学号',fontproperties='STSong',fontsize=15)
plt.ylabel('学生总成绩',fontproperties='STSong',rotation=360,fontsize=10)
plt.grid()
plt.subplot(223)
plt.bar(score.学号,sum_score)
plt.xticks(range(1001,1031),rotation=60)
plt.title('学生总成绩分布条形图',fontproperties='STSong',fontsize=15)
plt.xlabel('学号',fontproperties='STSong',fontsize=15)
plt.ylabel('学生总成绩',fontproperties='STSong',rotation=360,fontsize=10)
plt.grid()
plt.subplot(224)
plt.title('每门课程箱线图',fontproperties='STSong')
plt.xlabel('课程名',fontproperties='STSong')
plt.ylabel('分数',fontproperties='STSong',rotation=360)
label = ['math','English','Python']
s = (score.高数,score.英语,score.python)
plt.boxplot(s,labels = label)
plt.grid()
plt.show()
